name: crud_flutter_api
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.7
  animated_text_kit: ^4.2.2
  intl: ^0.19.0
  http: ^1.1.0
  bot_toast: ^4.0.4
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  animations: ^2.0.3
  font_awesome_flutter: ^10.1.0
  carousel_slider: ^4.2.1
  flutter_map: ^6.1.0
  flutter_map_marker_popup: ^6.1.2
  latlong2: ^0.9.0
  easy_search_bar: ^2.5.0
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  geojson_vi: ^2.2.1
  flutter_map_geojson: ^1.0.6
  flutter_image_compress: ^2.1.0
  chewie: ^1.2.2
  video_player: ^2.3.2
  excel: ^2.0.7
  file_picker: ^5.2.10
  wakelock: ^0.6.2
  permission_handler: ^11.0.1
  flutter_map_marker_cluster: ^1.3.6

 
  

  


dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/img/
    - assets/gif/
    - assets/images/start/
    - assets/videos/
    - assets/geojson/

